sequenceDiagram
participant System_Inventory_Web_App as "System Inventory Web App"
participant System_Inventory_API as "System Inventory API"
participant Reporting_Consumers as "Reporting Consumers"
System_Inventory_Web_App->>System_Inventory_API: System Inventory Web App calls System Inventory API
System_Inventory_API->>Reporting_Consumers: System Inventory API sends Reporting Consumers